#Stage 1
FROM node:18.8-alpine as builder
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

#Stage 2
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /app/build .
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]
